# -*- coding: utf-8 -*-
"""CA2DataMining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVjEoO7534iXKh2t6KfA2AOT_ExnFSkS

#**Import Libaries**
"""

import string

import numpy as np
import pandas as pd

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.model_selection import StratifiedKFold
from imblearn.over_sampling import SMOTE
from sklearn import metrics
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from bs4 import BeautifulSoup
import re


from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from imblearn.combine import SMOTEENN  # Import SMOTEENN
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Data loading
df = pd.read_csv("SMSSpamCollection", sep='\t', header=None, names=["label", "message"])

df.head()

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

df.head()

df.info()

"""#Handling & Cleaning Text"""

#stemmer.stem('blessings')

"""### Text Preprocessing Function - BeautifulSoup

"""

# Preprocessing the data
def clean_text(text):
    """Clean and preprocess the text data"""
    # Remove HTML tags
    soup = BeautifulSoup(text, 'lxml')
    souped = soup.get_text()

    # Remove URLs, user mentions (@), and non-alphabetic characters
    souped = re.sub(r"(@|http://|https://|www)\S*", " ", souped)  # Remove URLs
    souped = re.sub(r"[^A-Za-z]+", " ", souped)  # Keep only alphabetic characters
    # Tokenize and remove stopwords
    tokens = nltk.word_tokenize(souped)
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

"""###Text Preprocessing Function - PoreterStemmer"""

stemmer = PorterStemmer()
corpus = []

stopwords_set = set(stopwords.words('english'))

for i in range(len(df)):
    message =df['message'].iloc[i].lower()
    message =message.translate(str.maketrans('', '', string.punctuation)).split()
    message =[stemmer.stem(word) for word in message if word not in stopwords_set]
    message =' '.join(message)
    corpus.append(message)

df.message.iloc[0]

corpus[0]

"""### Text Vectorization and Classification - Converts text data into Numerical data"""

tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the corpus using the TF-IDF vectorizer
X = tfidf_vectorizer.fit_transform(corpus)
y = df.label

#Train & Test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

# Cross-validation setup
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

#applying smote to balance the imbalance data
smote = SMOTE(random_state=42)

"""#Applying Both Model - Naive Bayes & SVC"""

# Initialize models
nb_model = MultinomialNB(alpha=0.01)
svc_model = LinearSVC()

# Lists to store scores
nb_scores = []
svc_scores = []

# Cross-validation and evaluation
for train_index, test_index in kf.split(X,y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    # Apply SMOTE to balance the data
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
    # Train and predict using Naive Bayes
    nb_model.fit(X_train_res, y_train_res)
    y_pred_nb = nb_model.predict(X_test)
    nb_scores.append(metrics.accuracy_score(y_test, y_pred_nb))
     # Train and predict using SVC
    svc_model.fit(X_train_res, y_train_res)
    y_pred_svc = svc_model.predict(X_test)
    svc_scores.append(metrics.accuracy_score(y_test, y_pred_svc))
    # Print detailed metrics for Naive Bayes  #This and the following print statements should be indented to be included in the for loop
    print("Naive Bayes - Classification Report:")
    print(metrics.classification_report(y_test, y_pred_nb))
    print("Naive Bayes - Confusion Matrix:")
    print(metrics.confusion_matrix(y_test, y_pred_nb))
        # Print detailed metrics for SVC
    print("SVC - Classification Report:")
    print(metrics.classification_report(y_test, y_pred_svc))
    print("SVC - Confusion Matrix:")
    print(metrics.confusion_matrix(y_test, y_pred_svc))

"""#### Created the density plot for Actual Vs Predicted for Both Naive Bayes and svc"""

sns.kdeplot(y_test, label="Actual")
sns.kdeplot(y_pred_nb, label="Predicted (Naive Bayes)")
plt.xlabel("Values")
plt.ylabel("Density")
plt.title("Density Plot: Actual vs. Predicted (Naive Bayes)")
plt.legend()
plt.show()

sns.kdeplot(y_test, label="Actual")
sns.kdeplot(y_pred_svc, label="Predicted (SVC)")
plt.xlabel("Values")
plt.ylabel("Density")
plt.title("Density Plot: Actual vs. Predicted (SVC)")
plt.legend()
plt.show()

def predict_message(message):
    """Predicts whether a message is ham or spam using the trained SVC model."""
    # Preprocess the message: apply the same preprocessing steps used for training data
    message = message.lower()
    message = message.translate(str.maketrans('', '', string.punctuation)).split()
    message = [stemmer.stem(word) for word in message if word not in stopwords_set]
    message = ' '.join(message)

    # Transform the message using the fitted TF-IDF vectorizer
    message_vector = tfidf_vectorizer.transform([message])

    # Make the prediction using the trained SVC model (you can replace with nb_model if desired)
    prediction = nb_model.predict(message_vector)[0]

    return prediction

# Accept user input for a new message

new_message = input("Enter a message to classify as ham or spam: ")

# Get the prediction
prediction = predict_message(new_message)

# Output the result
if prediction == 0:
    print("The message is classified as ham.")
else:
    print("The message is classified as spam.")

